version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    networks:
      - mongo-net
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - mongo-net

  python-app:
    image: python:3.10
    container_name: python_app_container
    volumes:
      - /tmp:/app
    environment:
      MONGO_URI: mongodb://root:root@mongodb:27017/mydatabase
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge

volumes:
  mongodb_data:
