version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: poc
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo_express1
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  python-app:
    image: python:3.10
    container_name: python_app1
    volumes:
      - ./your_python_app_directory:/app  # Corrigido o caminho do volume
    environment:
      MONGO_URI: mongodb://root:root@mongodb:27017/poc
    depends_on:
      - mongodb
